#define FALSE 0
#define TRUE 1

#define LOWERCASE_ASCII_TABLE_BASE 97
#define LOWERCASE_ASCII_TABLE_CEIL 122

#define CONVERT_TO_LOWER_CASE 32

#define UPPERCASE_ASCII_TABLE_BASE 65
#define UPPERCASE_ASCII_TABLE_CEIL 90